// Code generated by protoc-gen-go.
// source: aicloud/srv/example/proto/greeter/greeter.proto
// DO NOT EDIT!

/*
Package greeter is a generated protocol buffer package.

It is generated from these files:
	aicloud/srv/example/proto/greeter/greeter.proto

It has these top-level messages:
	PostRequest
	HelloRequest
	HelloResponse
	PostResponse
*/
package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostRequest struct {
	// bytes reward_rule = 1;
	//
	// Types that are valid to be assigned to TestOneof:
	//	*PostRequest_Test1
	//	*PostRequest_Test2
	TestOneof isPostRequest_TestOneof `protobuf_oneof:"test_oneof"`
	Hello     string                  `protobuf:"bytes,3,opt,name=hello" json:"hello" xml:"hello"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isPostRequest_TestOneof interface {
	isPostRequest_TestOneof()
}

type PostRequest_Test1 struct {
	Test1 string `protobuf:"bytes,1,opt,name=test1,oneof"`
}
type PostRequest_Test2 struct {
	Test2 string `protobuf:"bytes,2,opt,name=test2,oneof"`
}

func (*PostRequest_Test1) isPostRequest_TestOneof() {}
func (*PostRequest_Test2) isPostRequest_TestOneof() {}

func (m *PostRequest) GetTestOneof() isPostRequest_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *PostRequest) GetTest1() string {
	if x, ok := m.GetTestOneof().(*PostRequest_Test1); ok {
		return x.Test1
	}
	return ""
}

func (m *PostRequest) GetTest2() string {
	if x, ok := m.GetTestOneof().(*PostRequest_Test2); ok {
		return x.Test2
	}
	return ""
}

func (m *PostRequest) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PostRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PostRequest_OneofMarshaler, _PostRequest_OneofUnmarshaler, _PostRequest_OneofSizer, []interface{}{
		(*PostRequest_Test1)(nil),
		(*PostRequest_Test2)(nil),
	}
}

func _PostRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PostRequest)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *PostRequest_Test1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Test1)
	case *PostRequest_Test2:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Test2)
	case nil:
	default:
		return fmt.Errorf("PostRequest.TestOneof has unexpected type %T", x)
	}
	return nil
}

func _PostRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PostRequest)
	switch tag {
	case 1: // test_oneof.test1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &PostRequest_Test1{x}
		return true, err
	case 2: // test_oneof.test2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &PostRequest_Test2{x}
		return true, err
	default:
		return false, nil
	}
}

func _PostRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PostRequest)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *PostRequest_Test1:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Test1)))
		n += len(x.Test1)
	case *PostRequest_Test2:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Test2)))
		n += len(x.Test2)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name" xml:"name"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting string `protobuf:"bytes,2,opt,name=greeting" json:"greeting" xml:"greeting"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type PostResponse struct {
	Result     string `protobuf:"bytes,1,opt,name=result" json:"result" xml:"result"`
	RewardRule []byte `protobuf:"bytes,2,opt,name=reward_rule,json=rewardRule,proto3" json:"reward_rule" xml:"reward_rule"`
}

func (m *PostResponse) Reset()                    { *m = PostResponse{} }
func (m *PostResponse) String() string            { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()               {}
func (*PostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PostResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *PostResponse) GetRewardRule() []byte {
	if m != nil {
		return m.RewardRule
	}
	return nil
}

func init() {
	proto.RegisterType((*PostRequest)(nil), "PostRequest")
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*PostResponse)(nil), "PostResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Greeter service

type GreeterClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...client.CallOption) (*PostResponse, error)
}

type greeterClient struct {
	c           client.Client
	serviceName string
}

func NewGreeterClient(serviceName string, c client.Client) GreeterClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "greeter"
	}
	return &greeterClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *greeterClient) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Greeter.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Post(ctx context.Context, in *PostRequest, opts ...client.CallOption) (*PostResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Greeter.Post", in)
	out := new(PostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
	Post(context.Context, *PostRequest, *PostResponse) error
}

func RegisterGreeterHandler(s server.Server, hdlr GreeterHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Greeter{hdlr}, opts...))
}

type Greeter struct {
	GreeterHandler
}

func (h *Greeter) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.GreeterHandler.Hello(ctx, in, out)
}

func (h *Greeter) Post(ctx context.Context, in *PostRequest, out *PostResponse) error {
	return h.GreeterHandler.Post(ctx, in, out)
}

func init() { proto.RegisterFile("aicloud/srv/example/proto/greeter/greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x3b, 0x5d, 0xa7, 0xbe, 0xa5, 0x1e, 0x82, 0x8c, 0xd2, 0x8b, 0x12, 0x10, 0x06, 0x42,
	0x82, 0xf5, 0x3f, 0xf0, 0xb2, 0x1d, 0x25, 0x47, 0x2f, 0x23, 0xba, 0xe7, 0x1c, 0xa4, 0x4d, 0xcd,
	0x0f, 0xf5, 0xcf, 0x97, 0x26, 0xad, 0x74, 0xa7, 0xf6, 0xfb, 0xc9, 0xe3, 0x7d, 0x3f, 0x3c, 0x10,
	0xea, 0xf8, 0xae, 0x4d, 0xd8, 0x0b, 0x67, 0xbf, 0x05, 0xfe, 0xaa, 0xa6, 0xd3, 0x28, 0x3a, 0x6b,
	0xbc, 0x11, 0x07, 0x8b, 0xe8, 0xd1, 0x8e, 0x5f, 0x1e, 0x29, 0x53, 0xb0, 0x7c, 0x31, 0xce, 0x4b,
	0xfc, 0x0a, 0xe8, 0x3c, 0x5d, 0x41, 0xee, 0xd1, 0xf9, 0xc7, 0x72, 0x76, 0x37, 0x5b, 0x5f, 0x6d,
	0x33, 0x99, 0xe2, 0xc8, 0xeb, 0xf2, 0x6c, 0xca, 0x6b, 0x7a, 0x03, 0xf9, 0x27, 0x6a, 0x6d, 0xca,
	0xf3, 0x9e, 0xcb, 0x14, 0x9e, 0x09, 0x40, 0xff, 0xbc, 0x33, 0x2d, 0x9a, 0x0f, 0xc6, 0x80, 0x6c,
	0x7b, 0x3c, 0x76, 0x50, 0x98, 0xb7, 0xaa, 0xc1, 0x54, 0x21, 0xe3, 0x3f, 0x7b, 0x80, 0x62, 0x98,
	0x71, 0x9d, 0x69, 0x1d, 0xd2, 0x0a, 0x2e, 0xa3, 0xe8, 0xb1, 0x3d, 0xa4, 0x4e, 0xf9, 0x9f, 0xd9,
	0x06, 0x48, 0x72, 0x1e, 0x66, 0x57, 0xb0, 0xb0, 0xe8, 0x82, 0xf6, 0xc3, 0xca, 0x21, 0xd1, 0x5b,
	0x58, 0x5a, 0xfc, 0x51, 0x76, 0xbf, 0xb3, 0x41, 0x63, 0x5c, 0x43, 0x24, 0x24, 0x24, 0x83, 0xc6,
	0xfa, 0x15, 0x2e, 0x36, 0xe9, 0x1a, 0x74, 0x0d, 0x79, 0x14, 0xa0, 0x05, 0x9f, 0xca, 0x56, 0xd7,
	0xfc, 0xc4, 0x8b, 0x65, 0xf4, 0x1e, 0xe6, 0x7d, 0x3b, 0x25, 0x7c, 0x72, 0xb8, 0xaa, 0xe0, 0x53,
	0x25, 0x96, 0xbd, 0x2d, 0xe2, 0x7d, 0x9f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9d, 0xf9,
	0xd5, 0x92, 0x01, 0x00, 0x00,
}
